version: '3'
services:
    web:
        image: webdevops/php-nginx:7.4
        container_name: web
        restart: always
        volumes:
            - ./:/app
        ports:
            - '8080:80'
        environment:
            WEB_DOCUMENT_ROOT: /app/public
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: laravel
            DB_USERNAME: user
            DB_PASSWORD: secret
        depends_on:
            - db

    db:
        image: mysql:5.7
        container_name: db
        restart: always
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
